import type { Metadata } from "next";
import { Lobster, Poppins } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import CardOne from "@/components/Card";
import CardTwo from "@/components/Card/CardTwo";
import Image from "next/image";
import { Notification, Setting2 } from "iconsax-react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Drizo Ads Dashboard",
  description: "Generated by Drizo TEAM",
};

const lobster = Lobster({
  subsets: ['latin'],
  weight: ['400']
})
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <div className="w-full h-14 fixed z-20 bg-black/70 backdrop-blur flex md:hidden items-center justify-between px-2">
          <h1 className={`font-medium text-2xl text-white ${lobster.className}`}>Drizo-Ads</h1>
          <div className='flex md:flex-col md:gap-5 gap-2'>
            <div className='flex justify-center items-center'>
              <button className='p-1 rounded-lg'>
                <Notification
                  size={19}
                  color='currentColor'
                  className='text-white'
                />
              </button>
            </div>
            <div className='flex justify-center items-center'>
              <button className='p-1 rounded-lg'>
                <Setting2
                  size={19}
                  color='currentColor'
                  className='text-white'
                />
              </button>
            </div>
            <div className='flex justify-center items-center'>
              <div className='flex relative w-8 h-8 rounded-full cursor-pointer justify-center items-center overflow-hidden'>
                <Image
                  src={"/images/user.jpeg"}
                  alt='user'
                  fill
                  className=''
                />
              </div>
            </div>
          </div>
        </div>
        <SideBar />
        <main className="md:pl-36 px-2 md:px-0 md:pb-0 pb-16 md:pt-5 pt-16 w-full relative flex flex-col-reverse md:flex-row gap-3 md:gap-0">
          <div className='flex flex-col md:gap-5 gap-3'>
            <CardOne />
            <CardTwo />
          </div>
          <div className="w-full md:px-5">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
